-- Final Demo Data for Assessment Service
-- Clean SQL with proper quote escaping

-- Insert Subjects
INSERT INTO assessment.subjects (name, description, class_level, display_order, created_at, updated_at, is_active) VALUES
('Mathematics - Basic', 'Elementary mathematics concepts', 'CLASS_6', 1, NOW(), NOW(), true),
('English - Basic', 'Basic English language and grammar', 'CLASS_6', 2, NOW(), NOW(), true),
('Science - Basic', 'Introduction to natural sciences', 'CLASS_6', 3, NOW(), NOW(), true),
('Social Studies - Basic', 'Basic social studies and civics', 'CLASS_6', 4, NOW(), NOW(), true),
('Hindi', 'Hindi language and literature', 'CLASS_6', 5, NOW(), NOW(), true),
('Mathematics - Intermediate', 'Intermediate mathematics with algebra', 'CLASS_7', 6, NOW(), NOW(), true),
('English - Intermediate', 'English literature and composition', 'CLASS_7', 7, NOW(), NOW(), true),
('Science - Intermediate', 'Physics, Chemistry, Biology basics', 'CLASS_7', 8, NOW(), NOW(), true),
('History', 'World and national history', 'CLASS_7', 9, NOW(), NOW(), true),
('Geography', 'Physical and human geography', 'CLASS_7', 10, NOW(), NOW(), true),
('Mathematics - Advanced', 'Advanced algebra and geometry', 'CLASS_8', 11, NOW(), NOW(), true),
('Physics', 'Mechanics, waves, and thermodynamics', 'CLASS_8', 12, NOW(), NOW(), true),
('Chemistry', 'Organic and inorganic chemistry', 'CLASS_8', 13, NOW(), NOW(), true),
('Biology', 'Cell biology and genetics', 'CLASS_8', 14, NOW(), NOW(), true),
('English Literature', 'Advanced literature analysis', 'CLASS_8', 15, NOW(), NOW(), true),
('Mathematics - Pre-Calculus', 'Trigonometry and pre-calculus', 'CLASS_9', 16, NOW(), NOW(), true),
('Physics - Mechanics', 'Classical mechanics and dynamics', 'CLASS_9', 17, NOW(), NOW(), true),
('Chemistry - Analytical', 'Analytical chemistry methods', 'CLASS_9', 18, NOW(), NOW(), true),
('Biology - Molecular', 'Molecular biology and biochemistry', 'CLASS_9', 19, NOW(), NOW(), true),
('Computer Science', 'Programming fundamentals', 'CLASS_9', 20, NOW(), NOW(), true),
('Mathematics - Advanced', 'Coordinate geometry and functions', 'CLASS_10', 21, NOW(), NOW(), true),
('Physics - Electricity', 'Current electricity and magnetism', 'CLASS_10', 22, NOW(), NOW(), true),
('Chemistry - Acids and Bases', 'Chemical reactions and equilibrium', 'CLASS_10', 23, NOW(), NOW(), true),
('Biology - Life Processes', 'Nutrition, respiration, circulation', 'CLASS_10', 24, NOW(), NOW(), true),
('Computer Applications', 'Programming and applications', 'CLASS_10', 25, NOW(), NOW(), true),
('Mathematics - Calculus', 'Differential and integral calculus', 'CLASS_11', 26, NOW(), NOW(), true),
('Physics - Modern Physics', 'Quantum mechanics and relativity', 'CLASS_11', 27, NOW(), NOW(), true),
('Chemistry - Organic', 'Organic chemistry reactions', 'CLASS_11', 28, NOW(), NOW(), true),
('Biology - Genetics', 'Heredity and evolution', 'CLASS_11', 29, NOW(), NOW(), true),
('Computer Science - Programming', 'Data structures and algorithms', 'CLASS_11', 30, NOW(), NOW(), true),
('Mathematics - Applied', 'Statistics and probability', 'CLASS_12', 31, NOW(), NOW(), true),
('Physics - Advanced', 'Optics and nuclear physics', 'CLASS_12', 32, NOW(), NOW(), true),
('Chemistry - Physical', 'Physical chemistry and kinetics', 'CLASS_12', 33, NOW(), NOW(), true),
('Biology - Biotechnology', 'Genetic engineering and applications', 'CLASS_12', 34, NOW(), NOW(), true),
('Computer Science - Advanced', 'Object oriented programming', 'CLASS_12', 35, NOW(), NOW(), true),
('Economics', 'Microeconomics and macroeconomics', 'CLASS_11', 36, NOW(), NOW(), true),
('Business Studies', 'Business management principles', 'CLASS_11', 37, NOW(), NOW(), true),
('Accountancy', 'Financial accounting', 'CLASS_11', 38, NOW(), NOW(), true),
('Political Science', 'Government and politics', 'CLASS_11', 39, NOW(), NOW(), true),
('Psychology', 'Introduction to psychology', 'CLASS_11', 40, NOW(), NOW(), true),
('Sociology', 'Society and social behavior', 'CLASS_12', 41, NOW(), NOW(), true),
('Philosophy', 'Logic and ethics', 'CLASS_12', 42, NOW(), NOW(), true),
('Fine Arts', 'Visual arts and creativity', 'CLASS_12', 43, NOW(), NOW(), true),
('Physical Education', 'Sports and fitness', 'CLASS_10', 44, NOW(), NOW(), true),
('Environmental Science', 'Ecology and conservation', 'CLASS_11', 45, NOW(), NOW(), true),
('Information Technology', 'IT fundamentals and applications', 'CLASS_10', 46, NOW(), NOW(), true),
('Biotechnology', 'Applied biology and technology', 'CLASS_12', 47, NOW(), NOW(), true),
('Statistics', 'Data analysis and interpretation', 'CLASS_11', 48, NOW(), NOW(), true),
('Engineering Drawing', 'Technical drawing and design', 'CLASS_11', 49, NOW(), NOW(), true),
('Agriculture', 'Crop science and farming', 'CLASS_12', 50, NOW(), NOW(), true);

-- Insert Topics
INSERT INTO assessment.topics (name, description, subject_id, display_order, created_at, updated_at, is_active) VALUES
('Number Systems', 'Rational and irrational numbers', 1, 1, NOW(), NOW(), true),
('Algebra', 'Linear equations and expressions', 1, 2, NOW(), NOW(), true),
('Geometry', 'Triangles and quadrilaterals', 1, 3, NOW(), NOW(), true),
('Mensuration', 'Area and perimeter calculations', 1, 4, NOW(), NOW(), true),
('Data Handling', 'Statistics and probability', 1, 5, NOW(), NOW(), true),
('Algebraic Expressions', 'Polynomials and factorization', 6, 6, NOW(), NOW(), true),
('Linear Equations', 'Solving linear equations', 6, 7, NOW(), NOW(), true),
('Coordinate Geometry', 'Cartesian plane and graphs', 11, 8, NOW(), NOW(), true),
('Quadratic Equations', 'Solving quadratic equations', 16, 9, NOW(), NOW(), true),
('Trigonometry', 'Trigonometric ratios and identities', 16, 10, NOW(), NOW(), true),
('Limits and Derivatives', 'Introduction to calculus', 26, 11, NOW(), NOW(), true),
('Integration', 'Integral calculus', 26, 12, NOW(), NOW(), true),
('Probability', 'Probability distributions', 31, 13, NOW(), NOW(), true),
('Statistics', 'Descriptive statistics', 31, 14, NOW(), NOW(), true),
('Vectors', 'Vector algebra and geometry', 26, 15, NOW(), NOW(), true),
('Matter and Materials', 'States of matter and properties', 3, 16, NOW(), NOW(), true),
('Motion and Force', 'Laws of motion', 3, 17, NOW(), NOW(), true),
('Light and Sound', 'Wave properties', 3, 18, NOW(), NOW(), true),
('Atomic Structure', 'Atoms and molecules', 13, 19, NOW(), NOW(), true),
('Periodic Classification', 'Periodic table trends', 13, 20, NOW(), NOW(), true),
('Chemical Reactions', 'Types of reactions', 13, 21, NOW(), NOW(), true),
('Acids, Bases and Salts', 'pH and neutralization', 23, 22, NOW(), NOW(), true),
('Metals and Non-metals', 'Properties and uses', 23, 23, NOW(), NOW(), true),
('Cell Structure', 'Plant and animal cells', 14, 24, NOW(), NOW(), true),
('Life Processes', 'Nutrition and respiration', 24, 25, NOW(), NOW(), true),
('Reproduction', 'Sexual and asexual reproduction', 24, 26, NOW(), NOW(), true),
('Heredity and Evolution', 'Genetics and natural selection', 29, 27, NOW(), NOW(), true),
('Biotechnology', 'Genetic engineering applications', 34, 28, NOW(), NOW(), true),
('Kinematics', 'Motion in one and two dimensions', 12, 29, NOW(), NOW(), true),
('Dynamics', 'Newton laws and applications', 17, 30, NOW(), NOW(), true),
('Energy and Power', 'Work, energy and power', 22, 31, NOW(), NOW(), true),
('Current Electricity', 'Electric circuits and resistance', 22, 32, NOW(), NOW(), true),
('Magnetic Effects', 'Magnetism and electromagnetic induction', 27, 33, NOW(), NOW(), true),
('Optics', 'Reflection and refraction', 32, 34, NOW(), NOW(), true),
('Modern Physics', 'Atomic and nuclear physics', 32, 35, NOW(), NOW(), true),
('Grammar', 'Parts of speech and tenses', 2, 36, NOW(), NOW(), true),
('Comprehension', 'Reading and understanding', 2, 37, NOW(), NOW(), true),
('Writing Skills', 'Essay and letter writing', 7, 38, NOW(), NOW(), true),
('Literature', 'Poetry and prose analysis', 15, 39, NOW(), NOW(), true),
('Vocabulary', 'Word meanings and usage', 15, 40, NOW(), NOW(), true),
('Programming Fundamentals', 'Variables and data types', 20, 41, NOW(), NOW(), true),
('Control Structures', 'Loops and conditions', 20, 42, NOW(), NOW(), true),
('Functions', 'Function definition and calling', 25, 43, NOW(), NOW(), true),
('Arrays', 'Array operations', 25, 44, NOW(), NOW(), true),
('Object Oriented Programming', 'Classes and objects', 30, 45, NOW(), NOW(), true),
('Data Structures', 'Stacks, queues, and trees', 35, 46, NOW(), NOW(), true),
('Algorithms', 'Sorting and searching', 35, 47, NOW(), NOW(), true),
('Database Management', 'SQL and database design', 46, 48, NOW(), NOW(), true),
('Ancient History', 'Indus Valley civilization', 9, 49, NOW(), NOW(), true),
('Medieval History', 'Mughal empire', 9, 50, NOW(), NOW(), true),
('Modern History', 'Freedom struggle', 9, 51, NOW(), NOW(), true),
('Physical Geography', 'Landforms and climate', 10, 52, NOW(), NOW(), true),
('Human Geography', 'Population and settlements', 10, 53, NOW(), NOW(), true);

-- Insert Questions
INSERT INTO assessment.questions (text, type, subject_id, topic_id, difficulty, correct_answer, explanation, points, created_by, created_at, updated_at, is_active) VALUES
('What is the value of square root of 144?', 'MCQ', 1, 1, 'EASY', '12', 'The square root of 144 is 12 because 12 × 12 = 144.', 1, 1, NOW(), NOW(), true),
('Solve: 2x + 5 = 13', 'MCQ', 1, 2, 'MEDIUM', 'x = 4', 'Subtract 5 from both sides: 2x = 8, then divide by 2: x = 4.', 2, 1, NOW(), NOW(), true),
('Find the area of a triangle with base 10 cm and height 8 cm', 'MCQ', 1, 3, 'EASY', '40 square cm', 'Area of triangle = (1/2) × base × height = (1/2) × 10 × 8 = 40 cm².', 1, 1, NOW(), NOW(), true),
('What is 25% of 80?', 'NUMERIC', 1, 5, 'EASY', '20', '25% = 25/100 = 0.25. So 0.25 × 80 = 20.', 1, 1, NOW(), NOW(), true),
('Factorize: x² - 9', 'MCQ', 6, 6, 'MEDIUM', '(x+3)(x-3)', 'This is a difference of squares: x² - 9 = x² - 3² = (x+3)(x-3).', 2, 1, NOW(), NOW(), true),
('Solve: 3x - 7 = 2x + 5', 'NUMERIC', 6, 7, 'MEDIUM', '12', 'Rearranging: 3x - 2x = 5 + 7, so x = 12.', 2, 1, NOW(), NOW(), true),
('Find the distance between points (1,2) and (4,6)', 'NUMERIC', 11, 8, 'HARD', '5', 'Distance = √[(4-1)² + (6-2)²] = √[9 + 16] = √25 = 5.', 3, 1, NOW(), NOW(), true),
('Solve: x² - 5x + 6 = 0', 'MCQ', 16, 9, 'HARD', 'x = 2, 3', 'Factoring: (x-2)(x-3) = 0, so x = 2 or x = 3.', 3, 1, NOW(), NOW(), true),
('Find sin(30°)', 'MCQ', 16, 10, 'MEDIUM', '1/2', 'sin(30°) = 1/2 is a standard trigonometric value.', 2, 1, NOW(), NOW(), true),
('Find the derivative of x³', 'MCQ', 26, 11, 'HARD', '3x²', 'Using power rule: d/dx(x³) = 3x²⁻¹ = 3x².', 3, 1, NOW(), NOW(), true),
('What is the chemical formula of water?', 'MCQ', 3, 16, 'EASY', 'H2O', 'Water consists of 2 hydrogen atoms and 1 oxygen atom.', 1, 1, NOW(), NOW(), true),
('Which gas is released during photosynthesis?', 'MCQ', 14, 24, 'EASY', 'Oxygen', 'Plants release oxygen as a byproduct of photosynthesis.', 1, 1, NOW(), NOW(), true),
('What is the atomic number of carbon?', 'NUMERIC', 13, 19, 'EASY', '6', 'Carbon has 6 protons, so its atomic number is 6.', 1, 1, NOW(), NOW(), true),
('State Newton first law of motion', 'ESSAY', 12, 29, 'MEDIUM', 'An object at rest stays at rest and an object in motion stays in motion unless acted upon by an external force', 'This is also known as the law of inertia.', 3, 1, NOW(), NOW(), true),
('What is the pH of pure water?', 'NUMERIC', 23, 22, 'MEDIUM', '7', 'Pure water is neutral with a pH of 7.', 2, 1, NOW(), NOW(), true),
('Name the powerhouse of the cell', 'FILL_BLANK', 14, 24, 'EASY', 'Mitochondria', 'Mitochondria produce ATP energy for cellular processes.', 1, 1, NOW(), NOW(), true),
('What is the speed of light in vacuum?', 'MCQ', 32, 35, 'HARD', '3 × 10⁸ m/s', 'Light travels at approximately 300,000,000 m/s in vacuum.', 3, 1, NOW(), NOW(), true),
('Define photosynthesis', 'ESSAY', 24, 25, 'MEDIUM', 'The process by which plants make food using sunlight, carbon dioxide and water', 'Photosynthesis converts light energy into chemical energy.', 3, 1, NOW(), NOW(), true),
('What is the unit of electric current?', 'MCQ', 22, 32, 'EASY', 'Ampere', 'Electric current is measured in amperes (A).', 1, 1, NOW(), NOW(), true),
('State Ohm law', 'ESSAY', 22, 32, 'MEDIUM', 'Current is directly proportional to voltage and inversely proportional to resistance', 'V = IR, where V is voltage, I is current, and R is resistance.', 3, 1, NOW(), NOW(), true),
('What is a noun?', 'MCQ', 2, 36, 'EASY', 'A naming word', 'Nouns are words that name people, places, things, or ideas.', 1, 1, NOW(), NOW(), true),
('Choose the correct past tense of "go"', 'MCQ', 2, 36, 'EASY', 'went', 'The past tense of "go" is "went" (irregular verb).', 1, 1, NOW(), NOW(), true),
('What is a metaphor?', 'MCQ', 15, 39, 'MEDIUM', 'A direct comparison without using like or as', 'Metaphors compare two unlike things directly.', 2, 1, NOW(), NOW(), true),
('Write a paragraph about your favorite hobby', 'ESSAY', 7, 38, 'MEDIUM', 'A well-structured paragraph with introduction, body, and conclusion', 'Should include topic sentence, supporting details, and conclusion.', 3, 1, NOW(), NOW(), true),
('Find the synonym of "happy"', 'MCQ', 15, 40, 'EASY', 'joyful', 'Joyful means the same as happy.', 1, 1, NOW(), NOW(), true),
('What is a variable in programming?', 'MCQ', 20, 41, 'EASY', 'A storage location with a name', 'Variables store data that can be referenced and modified.', 1, 1, NOW(), NOW(), true),
('What does "if" statement do?', 'MCQ', 20, 42, 'EASY', 'Makes decisions in code', 'If statements execute code based on conditions.', 1, 1, NOW(), NOW(), true),
('What is the purpose of a function?', 'MCQ', 25, 43, 'MEDIUM', 'To organize code into reusable blocks', 'Functions help in code modularity and reusability.', 2, 1, NOW(), NOW(), true),
('What is an array?', 'MCQ', 25, 44, 'MEDIUM', 'A collection of similar data types', 'Arrays store multiple values of the same type.', 2, 1, NOW(), NOW(), true),
('Define object-oriented programming', 'ESSAY', 30, 45, 'HARD', 'Programming paradigm based on objects containing data and methods', 'OOP includes concepts like encapsulation, inheritance, and polymorphism.', 3, 1, NOW(), NOW(), true),
('What is the time complexity of binary search?', 'MCQ', 35, 47, 'HARD', 'O(log n)', 'Binary search halves the search space in each iteration.', 3, 1, NOW(), NOW(), true),
('The Earth is round', 'TRUE_FALSE', 3, 16, 'EASY', 'True', 'The Earth is approximately spherical in shape.', 1, 1, NOW(), NOW(), true),
('Water boils at 90°C', 'TRUE_FALSE', 3, 16, 'EASY', 'False', 'Water boils at 100°C at standard atmospheric pressure.', 1, 1, NOW(), NOW(), true),
('Photosynthesis occurs only during day', 'TRUE_FALSE', 14, 24, 'MEDIUM', 'True', 'Photosynthesis requires sunlight, so it occurs during the day.', 2, 1, NOW(), NOW(), true),
('Python is a programming language', 'TRUE_FALSE', 20, 41, 'EASY', 'True', 'Python is indeed a popular programming language.', 1, 1, NOW(), NOW(), true),
('HTML stands for HyperText Markup Language', 'TRUE_FALSE', 46, 48, 'EASY', 'True', 'HTML is HyperText Markup Language.', 1, 1, NOW(), NOW(), true),
('What is 15% of 200?', 'NUMERIC', 1, 5, 'EASY', '30', '15% of 200 = 0.15 × 200 = 30.', 1, 1, NOW(), NOW(), true),
('Find the perimeter of a rectangle with length 8 cm and width 5 cm', 'NUMERIC', 1, 4, 'EASY', '26', 'Perimeter = 2(l + w) = 2(8 + 5) = 26 cm.', 1, 1, NOW(), NOW(), true),
('Solve: 5x = 25', 'NUMERIC', 6, 7, 'EASY', '5', 'Divide both sides by 5: x = 25/5 = 5.', 1, 1, NOW(), NOW(), true),
('What is the sum of angles in a triangle?', 'NUMERIC', 1, 3, 'EASY', '180', 'The sum of all angles in any triangle is 180°.', 1, 1, NOW(), NOW(), true),
('Find the value of 2³', 'NUMERIC', 1, 1, 'EASY', '8', '2³ = 2 × 2 × 2 = 8.', 1, 1, NOW(), NOW(), true),
('How many bones are in human body?', 'NUMERIC', 14, 24, 'MEDIUM', '206', 'Adult human body has 206 bones.', 2, 1, NOW(), NOW(), true),
('What is the boiling point of water in Fahrenheit?', 'NUMERIC', 3, 16, 'EASY', '212', 'Water boils at 212°F.', 1, 1, NOW(), NOW(), true),
('Name the largest planet in solar system', 'FILL_BLANK', 3, 16, 'EASY', 'Jupiter', 'Jupiter is the largest planet in our solar system.', 1, 1, NOW(), NOW(), true),
('What is the chemical symbol for gold?', 'FILL_BLANK', 13, 19, 'MEDIUM', 'Au', 'Gold symbol is Au from Latin aurum.', 2, 1, NOW(), NOW(), true),
('How many chambers does human heart have?', 'NUMERIC', 14, 24, 'EASY', '4', 'Human heart has 4 chambers: 2 atria and 2 ventricles.', 1, 1, NOW(), NOW(), true),
('What gas do plants absorb during photosynthesis?', 'FILL_BLANK', 24, 25, 'EASY', 'Carbon dioxide', 'Plants absorb CO₂ and release oxygen.', 1, 1, NOW(), NOW(), true),
('Who was the first Prime Minister of India?', 'FILL_BLANK', 9, 51, 'EASY', 'Jawaharlal Nehru', 'Nehru was India first PM after independence.', 1, 1, NOW(), NOW(), true),
('In which year did India gain independence?', 'NUMERIC', 9, 51, 'EASY', '1947', 'India gained independence on August 15, 1947.', 1, 1, NOW(), NOW(), true),
('What is the capital of India?', 'FILL_BLANK', 10, 53, 'EASY', 'New Delhi', 'New Delhi is the capital city of India.', 1, 1, NOW(), NOW(), true),
('Name the longest river in India', 'FILL_BLANK', 10, 52, 'MEDIUM', 'Ganga', 'River Ganga is the longest river in India.', 2, 1, NOW(), NOW(), true);

-- Add question options for MCQ questions
INSERT INTO assessment.question_options (question_id, option_text) VALUES
(1, '10'), (1, '11'), (1, '12'), (1, '13'),
(2, 'x = 3'), (2, 'x = 4'), (2, 'x = 5'), (2, 'x = 6'),
(3, '30 square cm'), (3, '40 square cm'), (3, '50 square cm'), (3, '80 square cm'),
(5, '(x+3)(x-3)'), (5, '(x+9)(x-1)'), (5, '(x+1)(x-9)'), (5, '(x-3)²'),
(8, 'x = 1, 6'), (8, 'x = 2, 3'), (8, 'x = -2, -3'), (8, 'x = 0, 5'),
(9, '1/2'), (9, '√2/2'), (9, '√3/2'), (9, '1'),
(10, 'x²'), (10, '3x²'), (10, '3x³'), (10, 'x³/3'),
(11, 'H2O'), (11, 'H2O2'), (11, 'HO'), (11, 'H3O'),
(12, 'Carbon dioxide'), (12, 'Oxygen'), (12, 'Nitrogen'), (12, 'Hydrogen'),
(17, '3 × 10⁸ m/s'), (17, '3 × 10⁶ m/s'), (17, '3 × 10⁷ m/s'), (17, '3 × 10⁹ m/s'),
(19, 'Volt'), (19, 'Ampere'), (19, 'Ohm'), (19, 'Watt'),
(21, 'A naming word'), (21, 'An action word'), (21, 'A describing word'), (21, 'A joining word'),
(22, 'goed'), (22, 'went'), (22, 'gone'), (22, 'going'),
(23, 'A direct comparison without using like or as'), (23, 'A comparison using like or as'), (23, 'An exaggeration'), (23, 'A question'),
(25, 'sad'), (25, 'angry'), (25, 'joyful'), (25, 'tired'),
(26, 'A storage location with a name'), (26, 'A type of loop'), (26, 'A function'), (26, 'An operator'),
(27, 'Makes decisions in code'), (27, 'Repeats code'), (27, 'Stores data'), (27, 'Prints output'),
(28, 'To store data'), (28, 'To organize code into reusable blocks'), (28, 'To make decisions'), (28, 'To repeat code'),
(29, 'A single variable'), (29, 'A collection of similar data types'), (29, 'A function'), (29, 'A loop'),
(31, 'O(n)'), (31, 'O(log n)'), (31, 'O(n²)'), (31, 'O(1)');

-- Insert Daily Questions
INSERT INTO assessment.daily_questions (date, question_id, subject_id, difficulty, points, created_at) VALUES
(CURRENT_DATE, 1, 1, 'EASY', 1, NOW()),
(CURRENT_DATE, 11, 3, 'EASY', 1, NOW()),
(CURRENT_DATE, 21, 2, 'EASY', 1, NOW()),
(CURRENT_DATE, 26, 20, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '1 day', 2, 1, 'MEDIUM', 2, NOW()),
(CURRENT_DATE - INTERVAL '1 day', 12, 14, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '2 days', 3, 1, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '2 days', 13, 13, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '3 days', 4, 1, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '3 days', 16, 14, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '4 days', 5, 6, 'MEDIUM', 2, NOW()),
(CURRENT_DATE - INTERVAL '4 days', 19, 22, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '5 days', 6, 6, 'MEDIUM', 2, NOW()),
(CURRENT_DATE - INTERVAL '6 days', 7, 11, 'HARD', 3, NOW()),
(CURRENT_DATE - INTERVAL '7 days', 8, 16, 'HARD', 3, NOW()),
(CURRENT_DATE - INTERVAL '8 days', 9, 16, 'MEDIUM', 2, NOW()),
(CURRENT_DATE - INTERVAL '9 days', 10, 26, 'HARD', 3, NOW()),
(CURRENT_DATE - INTERVAL '10 days', 27, 20, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '11 days', 32, 3, 'EASY', 1, NOW()),
(CURRENT_DATE - INTERVAL '12 days', 35, 20, 'EASY', 1, NOW());

-- Insert User Submissions
INSERT INTO assessment.user_submissions (user_id, question_id, answer, is_correct, time_taken, points_earned, is_daily_question, submitted_at) VALUES
(2, 1, '12', true, 30, 1, true, NOW() - INTERVAL '1 hour'),
(2, 2, 'x = 4', true, 60, 2, false, NOW() - INTERVAL '2 hours'),
(2, 3, '40 square cm', true, 45, 1, false, NOW() - INTERVAL '3 hours'),
(2, 4, '20', true, 25, 1, false, NOW() - INTERVAL '4 hours'),
(2, 5, '(x+3)(x-3)', true, 90, 2, false, NOW() - INTERVAL '5 hours'),
(2, 11, 'H2O', true, 20, 1, true, NOW() - INTERVAL '1 day'),
(2, 12, 'Oxygen', true, 15, 1, false, NOW() - INTERVAL '1 day'),
(2, 13, '6', true, 35, 1, false, NOW() - INTERVAL '1 day'),
(2, 21, 'A naming word', true, 25, 1, true, NOW() - INTERVAL '2 days'),
(2, 22, 'went', true, 20, 1, false, NOW() - INTERVAL '2 days'),
(2, 26, 'A storage location with a name', true, 40, 1, true, NOW() - INTERVAL '3 days'),
(2, 32, 'True', true, 15, 1, true, NOW() - INTERVAL '4 days'),
(2, 33, 'False', true, 10, 1, false, NOW() - INTERVAL '4 days'),
(2, 34, 'True', true, 12, 2, true, NOW() - INTERVAL '5 days'),
(2, 35, 'True', true, 8, 1, false, NOW() - INTERVAL '5 days');

-- Insert User Streaks
INSERT INTO assessment.user_streaks (user_id, subject_id, current_streak, longest_streak, last_activity, is_active, created_at, updated_at) VALUES
(2, 1, 8, 15, CURRENT_DATE, true, NOW() - INTERVAL '15 days', NOW()),
(2, 3, 5, 10, CURRENT_DATE - INTERVAL '1 day', true, NOW() - INTERVAL '20 days', NOW()),
(2, 2, 3, 7, CURRENT_DATE - INTERVAL '2 days', true, NOW() - INTERVAL '25 days', NOW()),
(2, 20, 6, 12, CURRENT_DATE - INTERVAL '3 days', true, NOW() - INTERVAL '30 days', NOW()),
(2, 14, 2, 8, CURRENT_DATE - INTERVAL '4 days', true, NOW() - INTERVAL '35 days', NOW());

-- Insert Live Exams
INSERT INTO assessment.live_exams (title, description, subject_id, class_level, duration, instructions, passing_score, scheduled_at, status, total_participants, created_at, updated_at) VALUES
('Mathematics Live Quiz', 'Algebra and geometry quiz', 1, 'CLASS_6', 60, 'Answer all questions carefully', 70, NOW() + INTERVAL '2 hours', 'SCHEDULED', 0, NOW(), NOW()),
('Science Test - Basic', 'Matter and energy concepts', 3, 'CLASS_6', 45, 'Multiple choice questions', 65, NOW() + INTERVAL '1 day', 'SCHEDULED', 0, NOW(), NOW()),
('English Grammar Test', 'Parts of speech and tenses', 2, 'CLASS_6', 50, 'Grammar and vocabulary', 60, NOW() + INTERVAL '2 days', 'SCHEDULED', 0, NOW(), NOW()),
('Physics Live Exam', 'Mechanics and motion', 12, 'CLASS_8', 75, 'Solve with proper steps', 75, NOW() + INTERVAL '3 days', 'SCHEDULED', 0, NOW(), NOW()),
('Computer Programming', 'Basic programming concepts', 20, 'CLASS_9', 90, 'Programming fundamentals', 70, NOW() + INTERVAL '4 days', 'SCHEDULED', 0, NOW(), NOW()),
('Math Challenge - Completed', 'Algebra challenge', 6, 'CLASS_7', 60, 'Solve algebraic problems', 70, NOW() - INTERVAL '1 day', 'COMPLETED', 25, NOW() - INTERVAL '1 day', NOW()),
('Science Quiz - Done', 'Basic science concepts', 8, 'CLASS_7', 45, 'Multiple choice', 65, NOW() - INTERVAL '2 days', 'COMPLETED', 30, NOW() - INTERVAL '2 days', NOW());

-- Insert Contests
INSERT INTO assessment.contests (title, description, duration, start_time, end_time, rules, status, type, participants, created_at, updated_at) VALUES
('Math Olympiad 2024', 'Annual mathematics competition for all classes', 120, NOW() + INTERVAL '1 week', NOW() + INTERVAL '1 week 2 hours', 'No calculators allowed. Show all working.', 'UPCOMING', 'ACCURACY', 0, NOW(), NOW()),
('Science Fair Quiz', 'Inter-school science competition', 90, NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days 90 minutes', 'Multiple choice questions only', 'UPCOMING', 'SPEED', 0, NOW(), NOW()),
('Programming Championship', 'Coding contest for students', 180, NOW() + INTERVAL '2 weeks', NOW() + INTERVAL '2 weeks 3 hours', 'Use any programming language', 'UPCOMING', 'CODING', 0, NOW(), NOW()),
('Regional Quiz Bowl', 'Multi-subject competition', 150, NOW() - INTERVAL '1 week', NOW() - INTERVAL '1 week' + INTERVAL '150 minutes', 'Team participation allowed', 'COMPLETED', 'MIXED', 45, NOW() - INTERVAL '1 week', NOW()),
('Biology Challenge', 'Life sciences quiz', 90, NOW() - INTERVAL '2 weeks', NOW() - INTERVAL '2 weeks' + INTERVAL '90 minutes', 'Individual participation only', 'COMPLETED', 'ACCURACY', 32, NOW() - INTERVAL '2 weeks', NOW());

-- Insert Personalized Exams
INSERT INTO assessment.personalized_exams (user_id, title, description, subject_id, class_level, duration, total_questions, instructions, passing_score, status, score, correct_answers, incorrect_answers, unanswered_questions, started_at, completed_at, created_at, updated_at) VALUES
(2, 'My Math Practice', 'Custom algebra practice test', 1, 'CLASS_6', 45, 10, 'Solve all questions step by step', 70, 'COMPLETED', 85, 8, 2, 0, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '3 hours', NOW()),
(2, 'Science Review', 'Chemistry and physics review', 3, 'CLASS_6', 30, 8, 'Multiple choice questions', 60, 'COMPLETED', 90, 7, 1, 0, NOW() - INTERVAL '1 day', NOW() - INTERVAL '23 hours', NOW() - INTERVAL '25 hours', NOW()),
(2, 'Programming Basics', 'Introduction to programming', 20, 'CLASS_9', 60, 12, 'Conceptual questions', 65, 'COMPLETED', 75, 9, 3, 0, NOW() - INTERVAL '2 days', NOW() - INTERVAL '46 hours', NOW() - INTERVAL '2 days', NOW()),
(2, 'English Grammar', 'Grammar and vocabulary test', 2, 'CLASS_6', 25, 6, 'Answer all questions', 70, 'SCHEDULED', 0, 0, 0, 0, NULL, NULL, NOW() - INTERVAL '1 hour', NOW()),
(2, 'Physics Challenge', 'Mechanics problems', 12, 'CLASS_8', 90, 15, 'Show all calculations', 75, 'ACTIVE', 0, 0, 0, 0, NOW() - INTERVAL '30 minutes', NULL, NOW() - INTERVAL '2 hours', NOW());

COMMIT;